[package]
name = "serde_serializer_quick_unsupported"
version = "1.0.0"
edition = "2024"
description = "Helper for implementing a serializer that supports a reduced subset of the serde data model"
authors = ["Thomas BESSOU <thomas.bessou@hotmail.fr>"]
repository = "https://github.com/Ten0/serde_serializer_quick_unsupported"
license = "MPL-2.0"

[dependencies]

[dev-dependencies]
serde = "1"